# Site settings
title: "Resume"
description: "Mirzabek Uulu Kubatbek"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mirzabek Uulu Kubatbek"
resume_title:                   "Frontend Developer"

# used for the contact button in _layouts/resume.html
resume_contact_telegram:           "https://t.me/casie2"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "Bishkek, Kyrgyzstan, 720000"

resume_header_contact_info:     "Bishkek, Kyrgyzstan, 720000 • +(996) (999) 97-90-90 • k.mirzabekuulu@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a detail-oriented person who takes pride in producing high-quality work. I enjoy working in a team environment, where I can collaborate and share my ideas with other developers. I have also completed several projects where I was responsible for developing user interfaces.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Kubatbekkk"
  resume_twitter_url:           "http://twitter.com/falangaga"
  resume_dribbble_url:          "https://dribbble.com/iamfalanga"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/kubatbekk/"
  resume_instagram_url:         "https://www.instagram.com/212cmq/"
  resume_website_url:           "https://kubatbekkk.github.io/cv/"
  resume_medium_url:            "https://medium.com/@kubatmirzabekuulu"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
